import type { SpkRow } from '@/components/spk/types';

export const sampleSpkRows: SpkRow[] = [
    {
        id: '1',
        produksiNo: '2026/PRD/00256',
        tipeProduksi: 'Stock',
        customer: '-',
        item: 'Bangle',
        description: 'Bangle sample',
        itemId: '1',
        orderDate: '16-Jul-2026',
        workEstimated: 30,
        estimatedDelivery: '15-Aug-2026',
        status: 'Approved',
        prosesTerakhir: '',
    },
    {
        id: '2',
        produksiNo: '2026/PRD/00255',
        tipeProduksi: 'Pesanan',
        customer: 'James Wijaya',
        item: 'Pendant',
        description: 'Pendant sample',
        itemId: '2',
        orderDate: '16-Jul-2026',
        workEstimated: 3,
        estimatedDelivery: '15-Aug-2026',
        status: 'Approved',
        prosesTerakhir: '',
    },
    {
        id: '3',
        produksiNo: '2026/PRD/00254',
        tipeProduksi: 'Stock',
        customer: '-',
        item: 'Pendant',
        description: 'Pendant stock',
        itemId: '2',
        orderDate: '16-Jul-2026',
        workEstimated: 30,
        estimatedDelivery: '15-Aug-2026',
        status: 'Pengajuan Approval',
        prosesTerakhir: '',
    },
    {
        id: '4',
        produksiNo: '2026/PRD/00253',
        tipeProduksi: 'Pesanan',
        customer: 'Alex',
        item: 'Ladies Ring',
        description: 'Ladies ring sample',
        itemId: '3',
        orderDate: '16-Jul-2026',
        workEstimated: 3,
        estimatedDelivery: '15-Aug-2026',
        status: 'Pengajuan Approval',
        prosesTerakhir: '',
    },
];
